{"name": "not authenticated user -- @1.13 cases", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 29, in step_impl\n    assert actual_result == boolean\n"}, "steps": [{"name": "Given alien makes get request: /reconciliation/status/", "status": "passed", "start": 1610694036701, "stop": 1610694036729}, {"name": "Then check response of request: Authentication credentials were not provided. is True", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 29, in step_impl\n    assert actual_result == boolean\n"}, "start": 1610694036730, "stop": 1610694036733}], "parameters": [{"name": "url", "value": "/reconciliation/status/"}, {"name": "method", "value": "get"}, {"name": "bool", "value": "True"}], "start": 1610694036700, "stop": 1610694036735, "uuid": "4ab88320-f6f2-40bb-887c-349759dd4dad", "historyId": "d3e18fdcfa3cf024468fb4788d7c344c", "fullName": "features/III-reconciliation_access.feature:not authenticated user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}