{"name": "not authenticated user -- @1.14 cases", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 29, in step_impl\n    assert actual_result == boolean\n"}, "steps": [{"name": "Given alien makes post request: /reconciliation/status/", "status": "passed", "start": 1610694036747, "stop": 1610694036780}, {"name": "Then check response of request: Authentication credentials were not provided. is True", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 29, in step_impl\n    assert actual_result == boolean\n"}, "start": 1610694036780, "stop": 1610694036782}], "parameters": [{"name": "url", "value": "/reconciliation/status/"}, {"name": "method", "value": "post"}, {"name": "bool", "value": "True"}], "start": 1610694036741, "stop": 1610694036783, "uuid": "8606d899-cb66-4110-98bf-3b4e5842b68b", "historyId": "8549902b6bce57d707aa81fd9c5b34d9", "fullName": "features/III-reconciliation_access.feature:not authenticated user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}