{"name": "risk user -- @1.12 cases", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 36, in step_impl\n    assert actual_result == eval(boolean)\n"}, "steps": [{"name": "Given manager makes post request: /reconciliation/status/", "status": "passed", "start": 1610701062602, "stop": 1610701062696}, {"name": "Then check response of request: You do not have permission to perform this action. is False", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 36, in step_impl\n    assert actual_result == eval(boolean)\n"}, "start": 1610701062696, "stop": 1610701062697}], "parameters": [{"name": "url", "value": "/reconciliation/status/"}, {"name": "method", "value": "post"}, {"name": "bool", "value": "False"}], "start": 1610701062601, "stop": 1610701062698, "uuid": "63b17748-bd01-4e6f-bc1d-8ed8b28a4a1c", "historyId": "5fa4208ab0943109402a0d3448940483", "fullName": "features/III-reconciliation_access.feature:risk user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}