{"name": "risk user -- @1.13 cases", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 36, in step_impl\n    assert actual_result == eval(boolean)\n"}, "steps": [{"name": "Given manager makes get request: /reconciliation/status_accounts/", "status": "passed", "start": 1610701062700, "stop": 1610701062721}, {"name": "Then check response of request: You do not have permission to perform this action. is False", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 36, in step_impl\n    assert actual_result == eval(boolean)\n"}, "start": 1610701062721, "stop": 1610701062722}], "parameters": [{"name": "url", "value": "/reconciliation/status_accounts/"}, {"name": "method", "value": "get"}, {"name": "bool", "value": "False"}], "start": 1610701062699, "stop": 1610701062722, "uuid": "28258192-3cab-4b85-a59f-7dc592dbef8b", "historyId": "27ce79e617e820d9cb503554cec86f72", "fullName": "features/III-reconciliation_access.feature:risk user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}