{"name": "risk user -- @1.4 cases", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 36, in step_impl\n    assert actual_result == eval(boolean)\n"}, "steps": [{"name": "Given manager makes get request: /reconciliation/all_users_data/xlsx", "status": "passed", "start": 1610701062407, "stop": 1610701062428}, {"name": "Then check response of request: You do not have permission to perform this action. is False", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 36, in step_impl\n    assert actual_result == eval(boolean)\n"}, "start": 1610701062429, "stop": 1610701062429}], "parameters": [{"name": "url", "value": "/reconciliation/all_users_data/xlsx"}, {"name": "method", "value": "get"}, {"name": "bool", "value": "False"}], "start": 1610701062405, "stop": 1610701062430, "uuid": "17cdb181-ca65-43e6-b9ba-0f77d62dc5ab", "historyId": "ad308c72d421c1e6a04fe8711c9cc284", "fullName": "features/III-reconciliation_access.feature:risk user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}