{"name": "check reports update", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_II.py\", line 102, in step_impl\n    assert answer in response.text\n"}, "steps": [{"name": "Given check status of \"reports update\": false", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_II.py\", line 102, in step_impl\n    assert answer in response.text\n"}, "start": 1610726023249, "stop": 1610726023275}], "start": 1610726023247, "stop": 1610726023277, "uuid": "8b563807-17bc-43b9-820d-68993f08ac40", "historyId": "3f03cfe28a6a292071c86abc39e5a396", "fullName": "features/II-Reconciliation/II-reconciliation_risk.feature:check reports update", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "manager_user"}, {"name": "tag", "value": "super_user"}, {"name": "feature", "value": "check all user_data"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}