{"name": "manager user -- @1.7 cases", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 29, in step_impl\n    assert actual_result == eval(boolean)\n"}, "steps": [{"name": "Given alien makes get request: /reconciliation/import_hr/", "status": "passed", "start": 1610694652104, "stop": 1610694652128}, {"name": "Then check response of request: You do not have permission to perform this action. is True", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_access.py\", line 29, in step_impl\n    assert actual_result == eval(boolean)\n"}, "start": 1610694652129, "stop": 1610694652130}], "parameters": [{"name": "url", "value": "/reconciliation/import_hr/"}, {"name": "method", "value": "get"}, {"name": "bool", "value": "True"}], "start": 1610694652103, "stop": 1610694652130, "uuid": "73fa23ea-b99f-45eb-a041-7fc8f5d884e5", "historyId": "3aebe88a01c4503a2ed5bc728e8359b7", "fullName": "features/III-reconciliation_access.feature:manager user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}